import Head from 'next/head';
import Input from '../components/Input';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Manager | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Olá mundo</h1>
      </main>
    </div>
  );
}
