import Head from 'next/head';
import Header from '../components/Header';
import MenuMobile from '../components/MenuMobile';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Manager | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
      </main>
    </div>
  );
}
